Repository uselotus/lotus, pull requests merged in 2023-03, with the labels that each got.

#686 fix: correctly format bash scripts (#685)
  frontend/fonts/Alliance-No.2-Regular.woff
  frontend/src/index.css
  frontend/src/pages/ViewMetrics.tsx
  scripts/dev.sh
  scripts/self-host.sh
Labels: bug

#698 Diego/salesforce integration v1
  backend/Pipfile
  backend/Pipfile.lock
  backend/api/serializers/model_serializers.py
  backend/api/views.py
  backend/lotus/settings.py
  backend/lotus/urls.py
  backend/metering_billing/exceptions/exceptions.py
  backend/metering_billing/invoice.py
  backend/metering_billing/management/commands/setup_tasks.py
  backend/metering_billing/migrations/0229_historicalorganization_crm_settings_provisioned_and_more.py
  backend/metering_billing/migrations/0229_historicalsubscriptionrecord_subscription_filters_and_more.py
  backend/metering_billing/migrations/0232_merge_20230320_0050.py
  backend/metering_billing/models.py
  backend/metering_billing/serializers/model_serializers.py
  backend/metering_billing/serializers/request_serializers.py
  backend/metering_billing/tasks.py
  backend/metering_billing/utils/enums/enums.py
  backend/metering_billing/views/crm_views.py
  backend/metering_billing/views/model_views.py
  backend/metering_billing/webhooks.py
  backend/scripts/start_backend.dev.sh
  docker-compose.dev.yaml
  docs/api-reference/subscriptions/create-subscription.mdx
  docs/openapi.yaml
  docs/openapi_full.yaml
  docs/openapi_private.yaml
  frontend/cypress/e2e/spec.cy.ts
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/api/api.ts
  frontend/src/components/Customers/CustomerInfo.tsx
  frontend/src/components/Customers/CustomerInvoices.tsx
  frontend/src/components/Settings/settings/components/AppCard.tsx
  frontend/src/components/Settings/settings/tabs/IntegrationsTab.tsx
  frontend/src/config/Routes.tsx
  frontend/src/gen-types-camel.ts
  frontend/src/gen-types.ts
  frontend/src/helpers/quickStartCheck.tsx
  frontend/src/integrations/pages/SalesforceIntegrationView.tsx
  frontend/src/stores/useGlobalstore.ts
  frontend/src/types/account-type.ts
  frontend/src/types/crm-types.ts
  frontend/src/types/payment-processor-type.ts
  frontend/yarn.lock
Labels: request, WIP

#749 prefetch billing records
  backend/api/views.py
  backend/metering_billing/models.py
Labels: codeball:approved

#750 modularize lotus dev to make parts optional
  backend/Dockerfile
  backend/Pipfile
  backend/Pipfile.lock
  backend/api/serializers/model_serializers.py
  backend/api/views.py
  backend/lotus/settings.py
  backend/metering_billing/invoice.py
  backend/metering_billing/views/webhook_views.py
  backend/scripts/start_backend.dev.sh
  backend/scripts/start_backend.prod.sh
  backend/scripts/start_consumer.sh
  docker-compose.dev.yaml
  docs/contributing.mdx
  scripts/dev.sh
  scripts/self-host.sh
Labels: codeball:needs-careful-review

#751 event guidance posthog refactor
  go/event-guidance/main.go
  scripts/dev.sh
Labels: codeball:approved

#757 use prefetched plans in active version find
  backend/api/serializers/model_serializers.py
  backend/api/views.py
Labels: codeball:approved

#745 add e2e event tracking test
  .github/workflows/cypress.yml
  .github/workflows/events-e2e.yml
  .github/workflows/public_api_tests.yml
  .github/workflows/pytest.yml
  backend/api/views.py
  backend/lotus/settings.py
Labels: codeball:needs-careful-review

#715 feat: bulk pricing
  backend/metering_billing/migrations/0242_plancomponent_bulk_pricing_enabled_and_more.py
  backend/metering_billing/models.py
  backend/metering_billing/serializers/model_serializers.py
  backend/metering_billing/tests/test_components.py
  backend/metering_billing/tests/test_get_access.py
  backend/metering_billing/tests/test_metrics.py
  frontend/src/components/BreadCrumbs.tsx
  frontend/src/components/Plans/UsageComponentForm.tsx
  frontend/src/pages/CreatePlan.tsx
  frontend/src/pages/EditPlan.tsx
Labels: codeball:needs-careful-review

#748 Event feed gets a stream, needs pagination for search
  backend/metering_billing/serializers/request_serializers.py
  backend/metering_billing/views/model_views.py
  frontend/src/api/api.ts
  frontend/src/components/EventPreview.tsx
  frontend/src/components/Metrics/EventStream.tsx
  frontend/src/components/Metrics/useEventStream.ts
  frontend/src/gen-types-camel.ts
  frontend/src/gen-types.ts
  frontend/src/hooks/useDebounce.ts
  frontend/src/pages/ViewMetrics.tsx
Labels: codeball:needs-careful-review
